MODEL:
  TYPE: vit
  NAME: simmim_finetune_ablation
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: False
    USE_RPB: True
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: True
DATA:
  BATCH_SIZE: 116
  IMG_SIZE: 224
  TRAIN_CSV_PATH: "data/CheXpert-v1.0-small/train.csv"
  VAL_CSV_PATH: "data/CheXpert-v1.0-small/valid.csv"
  IMG_ROOT: "data/"
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  BASE_LR: 0.00125
  WARMUP_LR: 0.00000025
  MIN_LR: 0.00000025
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.65
AMP_OPT_LEVEL: "O0"
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_finetune__vit_base__img224__100ep_ablation
